/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import practicamp.Jugador;
import practicamp.Personaje;

/**
 *
 * @author noeli
 */
public class CambioModificadores extends javax.swing.JFrame {
    private ModificacionesPersonaje menu;
    private Jugador jugador;
    private Personaje personaje;
    /**
     * Creates new form CambioModificadores
     */
    public CambioModificadores(ModificacionesPersonaje menu,Jugador jugador,Personaje personaje) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.menu=menu;
        this.jugador=jugador;
        this.personaje=personaje;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDebilidades = new javax.swing.JButton();
        jFortalezas = new javax.swing.JButton();
        jVolver = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDebilidades.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jDebilidades.setForeground(new java.awt.Color(0, 16, 49));
        jDebilidades.setText("Debilidad");
        jDebilidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDebilidadesActionPerformed(evt);
            }
        });
        getContentPane().add(jDebilidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 240, 50));

        jFortalezas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jFortalezas.setForeground(new java.awt.Color(0, 16, 49));
        jFortalezas.setText("Fortaleza");
        jFortalezas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFortalezasActionPerformed(evt);
            }
        });
        getContentPane().add(jFortalezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 240, 50));

        jVolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jVolver.setForeground(new java.awt.Color(0, 16, 49));
        jVolver.setText("Volver");
        jVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 90, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo3.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDebilidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDebilidadesActionPerformed
        AñadirF_D forDeb =new AñadirF_D(menu,jugador,personaje,0);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jDebilidadesActionPerformed

    private void jFortalezasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFortalezasActionPerformed
        AñadirF_D forDeb =new AñadirF_D(menu,jugador,personaje,1);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jFortalezasActionPerformed

    private void jVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVolverActionPerformed
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_jVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioModificadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioModificadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioModificadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioModificadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CambioModificadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton jDebilidades;
    private javax.swing.JButton jFortalezas;
    private javax.swing.JButton jVolver;
    // End of variables declaration//GEN-END:variables
}
