/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author noeli
 */
public class CambioModificadores extends javax.swing.JFrame {

    /**
     * Creates new form CambioModificadores
     */
    public CambioModificadores() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDebilidades = new javax.swing.JButton();
        jFortalezas = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDebilidades.setBackground(new java.awt.Color(255, 255, 255));
        jDebilidades.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jDebilidades.setForeground(new java.awt.Color(0, 153, 0));
        jDebilidades.setText("Debilidad");
        jDebilidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDebilidadesActionPerformed(evt);
            }
        });
        getContentPane().add(jDebilidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 240, 50));

        jFortalezas.setBackground(new java.awt.Color(255, 255, 255));
        jFortalezas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jFortalezas.setForeground(new java.awt.Color(0, 153, 0));
        jFortalezas.setText("Fortaleza");
        getContentPane().add(jFortalezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 240, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5227842611_e65fa83134_b.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 411, 423));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDebilidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDebilidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDebilidadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioModificadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioModificadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioModificadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioModificadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambioModificadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton jDebilidades;
    private javax.swing.JButton jFortalezas;
    // End of variables declaration//GEN-END:variables
}
