/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import javax.swing.DefaultListModel;
import practicamp.Jugador;
import practicamp.Personaje;
import practicamp.Sistema;
import practicamp.Usuario;

/**
 *
 * @author noeli
 */
public class ElegirPersonaje extends javax.swing.JFrame {
    private Sistema sistema;
    private Menu_O menu;
    /**
     * Creates new form ElegirPersonaje
     */
    public ElegirPersonaje(Sistema sistema, Menu_O menu) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.sistema=sistema;
        this.menu=menu;
        DefaultListModel model = new DefaultListModel<>();        
        for (Jugador a: sistema.getUsuariosList()){
            String nombre = a.getPersonaje().getNombre();
            model.addElement(nombre);
        }
        jLista.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFondo2 = new javax.swing.JLabel();
        jVolver = new javax.swing.JButton();
        jAceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLista = new javax.swing.JList<>();
        jFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFondo2.setBackground(new java.awt.Color(0, 153, 0));
        jFondo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jFondo2.setForeground(new java.awt.Color(255, 255, 255));
        jFondo2.setText("Elija el personaje que desea modificar");
        jFondo2.setOpaque(true);
        getContentPane().add(jFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 280, 40));

        jVolver.setBackground(new java.awt.Color(255, 255, 255));
        jVolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jVolver.setForeground(new java.awt.Color(0, 102, 0));
        jVolver.setText("Volver");
        jVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jAceptar.setBackground(new java.awt.Color(255, 255, 255));
        jAceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jAceptar.setForeground(new java.awt.Color(0, 102, 0));
        jAceptar.setText("Aceptar");
        jAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(0, 102, 0));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jLista.setBackground(new java.awt.Color(0, 102, 0));
        jLista.setForeground(new java.awt.Color(255, 255, 255));
        jLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jLista);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, 190));

        jFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5227842611_e65fa83134_b.png"))); // NOI18N
        getContentPane().add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 417, 422));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVolverActionPerformed
       this.setVisible(false); 
       menu.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jVolverActionPerformed

    private void jAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAceptarActionPerformed
        Personaje pers = new Personaje();
        Jugador jug = null;
        for(Jugador u: sistema.getUsuariosList()){
        if (u.getPersonaje().getNombre().equals(jLista.getSelectedValue())){
            pers = u.getPersonaje();
            jug =u;
        }}
        this.setVisible(false);
        ModificacionesPersonaje mper= new ModificacionesPersonaje(pers,jug,sistema,menu,this);
        mper.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElegirPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElegirPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElegirPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElegirPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new ElegirPersonaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAceptar;
    private javax.swing.JLabel jFondo;
    private javax.swing.JLabel jFondo2;
    private javax.swing.JList<String> jLista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jVolver;
    // End of variables declaration//GEN-END:variables
}
