/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import practicamp.Demonio;
import practicamp.Esbirro;
import practicamp.Jugador;
import practicamp.Sistema;

/**
 *
 * @author Laura
 */
public class EsbirroDemonio extends javax.swing.JFrame {
    private Sistema sis;
    private Jugador jugador;
    private ComprarEsbirro compEsbi;
    private AniadirEsbirro anEsbi;
    private Menu menu;
    private ModificacionesPersonaje menuO;
    private Demonio demi;

    /**
     * Creates new form EsbirroDemonio
     */
    public EsbirroDemonio(Sistema sis, Jugador jugador, Demonio demi, ComprarEsbirro compEsbi, AniadirEsbirro anEsbi, Menu m,ModificacionesPersonaje mO) {
        initComponents();
        this.sis = sis;
        this.compEsbi = compEsbi;
        this.jugador = jugador;
        this.anEsbi = anEsbi;
        this.demi = demi;
        this.menu = m;
        this.menuO = mO;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
        DefaultListModel model = new DefaultListModel<>();  
        //Demonio demonio = new Demonio();
        for (Esbirro s: jugador.getPersonaje().getEsbirroList()){        
            if (s.getClass().equals(demi.getClass())){
            String nombre = s.getNombre();
            model.addElement(nombre); 
            //demi = (Demonio) s;            
            }            
        jList1.setModel(model);
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComprarEsbi = new javax.swing.JLabel();
        jAceptar = new javax.swing.JButton();
        jSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jEsbirrosDemonios = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComprarEsbi.setBackground(new java.awt.Color(102, 102, 0));
        jComprarEsbi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComprarEsbi.setForeground(new java.awt.Color(255, 255, 255));
        jComprarEsbi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jComprarEsbi.setText("Comprar esbirros");
        jComprarEsbi.setOpaque(true);
        getContentPane().add(jComprarEsbi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 40));

        jAceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jAceptar.setForeground(new java.awt.Color(51, 51, 0));
        jAceptar.setText("Aceptar");
        jAceptar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 60, -1));

        jSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSalir.setForeground(new java.awt.Color(51, 51, 0));
        jSalir.setText("Volver");
        jSalir.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 60, -1));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 102));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jList1.setBackground(new java.awt.Color(102, 102, 0));
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 360, 230));

        jEsbirrosDemonios.setBackground(new java.awt.Color(255, 255, 255));
        jEsbirrosDemonios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEsbirrosDemonios.setForeground(new java.awt.Color(51, 51, 0));
        jEsbirrosDemonios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEsbirrosDemonios.setText("Seleccione el esbirro demonio ");
        jEsbirrosDemonios.setOpaque(true);
        getContentPane().add(jEsbirrosDemonios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 360, 30));

        jLabelFondo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_neutro.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 416, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        this.setVisible(false);        
        if (compEsbi == null){
            anEsbi.setVisible(true);
        } else {
            compEsbi.setVisible(true);
        }
    }//GEN-LAST:event_jSalirActionPerformed

    private void jAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAceptarActionPerformed
        this.setVisible(false);
        String nombre = jList1.getSelectedValue();
        Demonio demonio = new Demonio();
        ArrayList<Esbirro> lista = new ArrayList<>();
        if (demi == null){
            lista = jugador.getPersonaje().getEsbirroList();                       
        } else {
            lista = demi.getListaEsbirrosD();
        }
        for (Esbirro s: lista){  
            if (nombre.equals(s.getNombre())){
                demonio = (Demonio) s;
            }
        } if (compEsbi == null){
            AniadirEsbirroDemonio adEsbi = new AniadirEsbirroDemonio(sis,jugador,this,anEsbi,demonio);
            //anEsbi.setVisible(true);
        } else{
            ComprarEsbirroDemonio comp = new ComprarEsbirroDemonio(sis,jugador,this,compEsbi,demonio);       
        }
    }//GEN-LAST:event_jAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EsbirroDemonio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EsbirroDemonio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EsbirroDemonio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EsbirroDemonio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new EsbirroDemonio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAceptar;
    private javax.swing.JLabel jComprarEsbi;
    private javax.swing.JLabel jEsbirrosDemonios;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JList<String> jList1;
    private javax.swing.JButton jSalir;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
