/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import javax.swing.JOptionPane;
import practicamp.Jugador;
import practicamp.Operador;
import practicamp.Sistema;
import practicamp.Usuario;

/**
 *
 * @author Victo
 */
public class inicioSesion extends javax.swing.JFrame {

    private String nombre;
    private String contraseña;
    private int accion;
    private Sistema sistema;
    private int modo;

    public inicioSesion(Sistema sistema, int modo) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.sistema = sistema;
        this.modo =modo;
    }

    public void error () {
        int val = JOptionPane.showConfirmDialog(null, "¿Volver a intentarlo?", "Credenciales incorrectas", JOptionPane.YES_NO_OPTION);
        if (val == 1) {
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jUsuario = new javax.swing.JLabel();
        jContraseña = new javax.swing.JLabel();
        jTextUsuario = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jSalir = new javax.swing.JButton();
        jInicioSesion = new javax.swing.JButton();
        Registrarse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jUsuario.setBackground(new java.awt.Color(0, 0, 102));
        jUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jUsuario.setText("Usuario:");
        getContentPane().add(jUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jContraseña.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jContraseña.setText("Contraseña:");
        getContentPane().add(jContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jTextUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jTextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 190, 30));

        jPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 190, 30));

        jSalir.setBackground(new java.awt.Color(255, 255, 255));
        jSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSalir.setForeground(new java.awt.Color(0, 0, 102));
        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jInicioSesion.setBackground(new java.awt.Color(255, 255, 255));
        jInicioSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jInicioSesion.setForeground(new java.awt.Color(0, 0, 102));
        jInicioSesion.setText("Iniciar sesión");
        jInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInicioSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        Registrarse.setBackground(new java.awt.Color(255, 255, 255));
        Registrarse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Registrarse.setForeground(new java.awt.Color(0, 0, 102));
        Registrarse.setText("Registrarse");
        Registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(Registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 340, 100));

        jFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 427, 413));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jSalirActionPerformed

    private void RegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseActionPerformed

        registro registrarse = new registro(sistema, modo, this);
        registrarse.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegistrarseActionPerformed

    private void jInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInicioSesionActionPerformed
        nombre = this.jTextUsuario.getText();
        char[] arrayC = jPassword.getPassword();
        String pass = new String(arrayC);
        contraseña = pass;
        if (sistema.personaCorrecta(nombre, contraseña,modo)) {
            if (modo==1){
            Jugador u= sistema.devolucionUsuario(nombre);
            if(u.isBaneado()==true){
                int val = JOptionPane.showConfirmDialog(null, "Tu cuenta ha sido baneada", "Usuario baneado", JOptionPane.YES_NO_OPTION);
                if (val == 1) {
                System.exit(0);
                }   
            }
            
            else{
            Menu menu = new Menu(u, sistema);
            menu.setVisible(true);
            this.setVisible(false);}}
            if (modo==0){
            Operador o= sistema.devolucionOperador(nombre);
            Menu_O menu = new Menu_O(o, sistema);
            menu.setVisible(true);
            this.setVisible(false);}
            
        } else {
            error();
        }

    }//GEN-LAST:event_jInicioSesionActionPerformed
    public String getNombre() {
        this.setVisible(true);
        return nombre;
    }

    public String getContraseña() {
        this.setVisible(true);
        return contraseña;
    }

    public int getAccion() {
        this.setVisible(true);
        return accion;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /*java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
                new inicioSesion().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registrarse;
    private javax.swing.JLabel jContraseña;
    private javax.swing.JLabel jFondo;
    private javax.swing.JButton jInicioSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JButton jSalir;
    private javax.swing.JTextField jTextUsuario;
    private javax.swing.JLabel jUsuario;
    // End of variables declaration//GEN-END:variables
}
