/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import practicamp.Jugador;
import practicamp.Sistema;

/**
 *
 * @author javii
 */
public class MenuDesafios extends javax.swing.JFrame {
    Menu menu;
    Sistema sistema;
    Jugador jugador;
    
    public MenuDesafios(Menu menu, Sistema sistema, Jugador jugador) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.menu = menu;
        this.sistema = sistema;
        this.jugador = jugador;
    }
    
    private void MenuNotificacion (int modo) {
        NotificacionesDesafios notificaciones = new NotificacionesDesafios (sistema,jugador,this,null,modo);
        this.setVisible(false);
        notificaciones.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();
        jButtonDesafiar = new javax.swing.JButton();
        jButtonEnviados = new javax.swing.JButton();
        jButtonRecibidos = new javax.swing.JButton();
        jButtonJugados = new javax.swing.JButton();
        jFoondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu.setBackground(new java.awt.Color(0, 0, 102));
        jMenu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jMenu.setForeground(new java.awt.Color(255, 255, 255));
        jMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu.setText("Menú");
        jMenu.setOpaque(true);
        getContentPane().add(jMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 40));

        jButtonVolver.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(0, 0, 102));
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jButtonDesafiar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDesafiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDesafiar.setForeground(new java.awt.Color(0, 0, 102));
        jButtonDesafiar.setText("Desafiar");
        jButtonDesafiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesafiarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDesafiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 220, -1));

        jButtonEnviados.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEnviados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEnviados.setForeground(new java.awt.Color(0, 0, 102));
        jButtonEnviados.setText("Desafios enviados");
        jButtonEnviados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviadosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnviados, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 220, -1));

        jButtonRecibidos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRecibidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRecibidos.setForeground(new java.awt.Color(0, 0, 102));
        jButtonRecibidos.setText("Desafios recibidos");
        jButtonRecibidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecibidosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRecibidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 220, -1));

        jButtonJugados.setBackground(new java.awt.Color(255, 255, 255));
        jButtonJugados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonJugados.setForeground(new java.awt.Color(0, 0, 102));
        jButtonJugados.setText("Desafios juagados");
        jButtonJugados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugadosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJugados, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 220, -1));

        jFoondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jFoondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonDesafiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesafiarActionPerformed
        DesafiarJugador desafiar = new DesafiarJugador(this,sistema,jugador);
        this.setVisible(false);
        desafiar.setVisible(true);
    }//GEN-LAST:event_jButtonDesafiarActionPerformed

    private void jButtonEnviadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviadosActionPerformed
        MenuNotificacion (0);
    }//GEN-LAST:event_jButtonEnviadosActionPerformed

    private void jButtonRecibidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecibidosActionPerformed
        MenuNotificacion (1);
    }//GEN-LAST:event_jButtonRecibidosActionPerformed

    private void jButtonJugadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugadosActionPerformed
        MenuNotificacion (2);
    }//GEN-LAST:event_jButtonJugadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDesafios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDesafios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDesafios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDesafios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDesafios().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDesafiar;
    private javax.swing.JButton jButtonEnviados;
    private javax.swing.JButton jButtonJugados;
    private javax.swing.JButton jButtonRecibidos;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jFoondo;
    private javax.swing.JLabel jMenu;
    // End of variables declaration//GEN-END:variables
}
