/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import practicamp.Cazador;
import practicamp.Jugador;
import practicamp.Licantropo;
import practicamp.Personaje;
import practicamp.Sistema;
import practicamp.Vampiro;

/**
 *
 * @author noeli
 */
public class NombrePersonaje extends javax.swing.JFrame {
    private Sistema sistema;
    private registrarPersonaje reg;
    private Jugador jugador;
    private int tipo;
    private Personaje personaje;
    private Menu menu;
    private int modo;
    private NotificacionesDesafios notificaciones;
    /**
     * Creates new form NombrePersonaje
     */
    public  NombrePersonaje(Sistema sistema, Menu menu, registrarPersonaje reg, Jugador jugador, int tipo,int modo,NotificacionesDesafios notificaciones) {
        initComponents();
        this.sistema = sistema;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.reg = reg;
        this.menu = menu;
        this.jugador = jugador;
        this.tipo = tipo;
        this.modo=modo;
        this.notificaciones=notificaciones;
        Personaje personaje = new Personaje();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jUsuario = new javax.swing.JLabel();
        jTextPersonaje = new javax.swing.JTextField();
        jFondo2 = new javax.swing.JLabel();
        jAceptar = new javax.swing.JButton();
        jVolver1 = new javax.swing.JButton();
        jFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("¿Cómo desea llamar a su personaje?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 310, 30));

        jUsuario.setBackground(new java.awt.Color(0, 0, 102));
        jUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jUsuario.setText(" Nombre:");
        getContentPane().add(jUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 90, -1));

        jTextPersonaje.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPersonajeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 190, 30));

        jFondo2.setBackground(new java.awt.Color(0, 16, 49));
        jFondo2.setOpaque(true);
        getContentPane().add(jFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 330, 120));

        jAceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jAceptar.setForeground(new java.awt.Color(0, 16, 49));
        jAceptar.setText("Aceptar");
        jAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        jVolver1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jVolver1.setForeground(new java.awt.Color(0, 16, 49));
        jVolver1.setText("Volver");
        jVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVolver1ActionPerformed(evt);
            }
        });
        getContentPane().add(jVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo3.jpg"))); // NOI18N
        getContentPane().add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPersonajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPersonajeActionPerformed

    private void jAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAceptarActionPerformed
        if (tipo == 0){
            this.personaje = new Cazador();
            //Cazador cazador = new Cazador();
            //jugador.setPersonaje(cazador);
        } else if (tipo == 1){
            this.personaje = new Licantropo();
        } else if (tipo == 2){
            this.personaje = new Vampiro();
        }
        personaje.setNombre(this.jTextPersonaje.getText());
        jugador.setPersonaje(personaje);
        try {
            sistema.guardarDatos();
            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(NombrePersonaje.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        if(modo==0){
         menu.setVisible(true);   
        }
        else{
        notificaciones.setVisible(true);
        }
    }//GEN-LAST:event_jAceptarActionPerformed

    private void jVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVolver1ActionPerformed
       if(modo==0){
        reg.setVisible(true);
        }
        else{
            notificaciones.setVisible(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jVolver1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NombrePersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NombrePersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NombrePersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NombrePersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new NombrePersonaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAceptar;
    private javax.swing.JLabel jFondo;
    private javax.swing.JLabel jFondo2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextPersonaje;
    private javax.swing.JLabel jUsuario;
    private javax.swing.JButton jVolver1;
    // End of variables declaration//GEN-END:variables
}
