/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import practicamp.Demonio;
import practicamp.Ghoul;
import practicamp.Humano;
import practicamp.Jugador;
import practicamp.Sistema;

/**
 *
 * @author Laura
 */
public class NombreEsbirro extends javax.swing.JFrame {
    private Sistema sis;
    private Jugador jugador;
    private int tipo;
    private int oro;
    private ComprarEsbirro comp;
    private ComprarEsbirroDemonio esbi;
    private Demonio demi;
    /**
     * Creates new form Esbirro
     */
    public NombreEsbirro(Sistema sis, ComprarEsbirro comp, ComprarEsbirroDemonio esbi, Jugador jugador, Demonio demi, int tipo) {
        initComponents();
        this.sis = sis;
        this.comp = comp;
        this.jugador = jugador;
        this.tipo = tipo;
        this.esbi = esbi;
        this.oro = jugador.getPersonaje().getCantidadOro();
        this.demi = demi;
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jUsuario = new javax.swing.JLabel();
        jTextEsbirro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jAceptar = new javax.swing.JButton();
        jVolver = new javax.swing.JButton();
        jFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jUsuario.setBackground(new java.awt.Color(0, 0, 102));
        jUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jUsuario.setText(" Nombre:");
        getContentPane().add(jUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 90, 20));

        jTextEsbirro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextEsbirro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEsbirroActionPerformed(evt);
            }
        });
        getContentPane().add(jTextEsbirro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 190, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("¿Como desea llamar a su esbirro?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 290, 30));

        jLabel1.setBackground(new java.awt.Color(0, 16, 49));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 330, 120));

        jAceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jAceptar.setForeground(new java.awt.Color(0, 16, 49));
        jAceptar.setText("Aceptar");
        jAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        jVolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jVolver.setForeground(new java.awt.Color(0, 16, 49));
        jVolver.setText("Volver");
        jVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo3.jpg"))); // NOI18N
        getContentPane().add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextEsbirroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEsbirroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEsbirroActionPerformed

    private void jAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAceptarActionPerformed
        if (tipo == 0){
            if(jugador.getPersonaje().getCantidadOro()>100){
            jugador.getPersonaje().setCantidadOro(oro-100); 
            }
            else{
               jugador.getPersonaje().setCantidadOro(0); 
            }           
            Demonio demonio = new Demonio();  
            demonio.setNombre(this.jTextEsbirro.getText());
            if (demi == null){
                jugador.getPersonaje().getEsbirroList().add(demonio);
            } else{
                demi.getListaEsbirrosD().add(demonio);
            }
        } else if (tipo == 1){
            if(jugador.getPersonaje().getCantidadOro()>20){
            jugador.getPersonaje().setCantidadOro(oro-20); 
            }
            else{
               jugador.getPersonaje().setCantidadOro(0); 
            }
            Ghoul ghoul = new Ghoul();
            ghoul.setNombre(this.jTextEsbirro.getText());
            if (demi == null){
                jugador.getPersonaje().getEsbirroList().add(ghoul);            
            } else {
                demi.getListaEsbirrosD().add(ghoul);
            }
        } else if (tipo == 2){
            if(jugador.getPersonaje().getCantidadOro()>50){
            jugador.getPersonaje().setCantidadOro(oro-50); 
            }
            else{
               jugador.getPersonaje().setCantidadOro(0); 
            }                                   
            Humano humano = new Humano();
            humano.setNombre(this.jTextEsbirro.getText());
            if (demi == null){
                jugador.getPersonaje().getEsbirroList().add(humano);            
            } else {
                demi.getListaEsbirrosD().add(humano);
            }        }            
        try {
            sis.guardarDatos();
        } catch (IOException ex) {
            Logger.getLogger(NombreEsbirro.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        if (comp == null){
            esbi.setVisible(true);
        } else {
            comp.setVisible(true);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jAceptarActionPerformed

    private void jVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVolverActionPerformed
        this.setVisible(false);
        comp.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NombreEsbirro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NombreEsbirro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NombreEsbirro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NombreEsbirro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new NombreEsbirro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAceptar;
    private javax.swing.JLabel jFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextEsbirro;
    private javax.swing.JLabel jUsuario;
    private javax.swing.JButton jVolver;
    // End of variables declaration//GEN-END:variables
}
